development:
  adapter: mysql2
  database: temp_database
  host: localhost
  username: root
  password: a

production:
  adapter: mysql2
  database: heroku_06e5330dde514f0
  host: mysql2://b1d67068e4608f:e979f241@us-cdbr-iron-east-02.cleardb.net/heroku_06e5330dde514f0?reconnect=true
  username: b1d67068e4608f
  password: e979f241

test:
  adapter: mysql2
  database: temp_database_test
  host: localhost
  username: root
  password: a