development:
  adapter: mysql2
  database: temp_database
  host: localhost
  username: root
  password: 

test:
  adapter: mysql2
  database: temp_database_test
  host: localhost
  username: root
  password: 