development:
  adapter: mysql2
  database: temp_database
  host: localhost
  username: root
  password: 

production:
  adapter: postgresql
  database: d2lrqlsun1e3pb
  host: ec2-184-73-165-193.compute-1.amazonaws.com
  username: pdqqtcvlcrdrrv
  password: KLMyOG-6wOov2G3jmn0yEAXsGA

test:
  adapter: mysql2
  database: temp_database_test
  host: localhost
  username: root
  password: 